# Generated by Django 3.1.7 on 2022-01-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220125_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoors', 'Indoors'), ('Delivered', 'Delivered'), ('Out of delivary', 'Out of delivary')], max_length=200, null=True),
        ),
    ]
