# Generated by Django 3.1.7 on 2022-01-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivary', 'Out for delivary')], default='Processing', max_length=200, null=True),
        ),
    ]
